Sol1
=====
- np.split사용

In [1]:
# Max_time = 4076.13 ms
# Memory = 31.1 MB
import numpy as np
def solution(arr):
    li = [np.array(arr)]
    n0, n1 = 0, 0 # 0, 1의 개수
    while li:
        array = li.pop()
        sum_n = np.sum(array)
        if sum_n == 0:
            n0 += 1
        elif sum_n == len(array)**2:
            n1 += 1
        else:
            sub = np.split(array, 2, axis = 0) # 행을 기준으로 array를 2개로 등분
            for i in sub:
                li.extend(np.split(i, 2, axis = 1)) # 열을 기준으로 array를 2개로 등분
    return [n0, n1]

### np.split()

In [12]:
li = np.array([1,2,3,]*4).reshape(4,3)
li

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [13]:
np.split(li, 2, axis = 0)

[array([[1, 2, 3],
        [1, 2, 3]]),
 array([[1, 2, 3],
        [1, 2, 3]])]

In [14]:
np.split(li, 4, axis = 0)

[array([[1, 2, 3]]),
 array([[1, 2, 3]]),
 array([[1, 2, 3]]),
 array([[1, 2, 3]])]

In [15]:
np.split(li, 3, axis = 1)

[array([[1],
        [1],
        [1],
        [1]]),
 array([[2],
        [2],
        [2],
        [2]]),
 array([[3],
        [3],
        [3],
        [3]])]

Sol2
===
- 재귀함수 사용
- 코드 속도 향상

In [18]:
# Max_time = 1773.84 ms
# Memory = 31 MB
import numpy as np
def solution(arr):
    def check(arr):
        sum_n = np.sum(arr)
        l = len(arr)
        if sum_n == 0:
            return np.array([1, 0])
        if sum_n == l**2:
            return np.array([0, 1])
        l //= 2
        return check(arr[:l, :l]) + check(arr[l:, :l]) + check(arr[:l, l:]) + check(arr[l:, l:])

    return check(np.array(arr)).tolist()


Sol3
====
- 재귀함수는 빠르지 않음
- 인덱싱이 속도를 빠르게 할 것으로 가정
- 확인결과 1번 코드에 np.split을 인덱싱으로 바꾸면 속도가 매우 빠름

In [ ]:
# Max_time = 1272.99 ms
# Memory = 31.3 MB
import numpy as np
def solution(arr):
    li = [np.array(arr)]
    n0, n1 = 0, 0 # 0, 1의 개수
    while li:
        array = li.pop()
        sum_n = np.sum(array)
        l = len(array)
        if sum_n == 0:
            n0 += 1
        elif sum_n == l**2:
            n1 += 1
        else:
            l //= 2
            li.extend([array[:l,:l], array[:l,l:], array[l:,:l], array[l:,l:]])

    return [n0, n1]